platform: x64

environment:
  matrix:
    - compiler: msvc
      generator: Visual Studio 14 Win64
      platform: x64
      configuration: Debug
      triplet: x64-windows

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-ragel"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-msvc.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat

build_script:
  - 'vcpkg install --recurse glib:%triplet% freetype:%triplet% cairo:%triplet%'
  - 'set PATH=%PATH%;C:\Program Files (x86)\MSBuild\14.0\Bin;c:\msys64\mingw64\bin' # msys2 is added just for having "ragel" on PATH
  - 'cd %APPVEYOR_BUILD_FOLDER%\harfbuzz-sys && cargo build --verbose --verbose'

cache:
  - c:\tools\vcpkg\installed\

# disable automatic tests
test: off
